"""initial schema

Revision ID: 79d2c2aa22c3
Revises: 
Create Date: 2026-09-22 15:47:00.101997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '79d2c2aa22c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column(
        'updated_at', sa.DateTime(), nullable=False,
        server_default=sa.text("now()"),
    ))
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_unique_constraint('uq_project_user_name', 'projects', ['user_id', 'name'])
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_unique_constraint('uq_tag_user_name', 'tags', ['user_id', 'name'])
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_constraint('uq_tag_user_name', 'tags', type_='unique')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_constraint('uq_project_user_name', 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'updated_at')
    # ### end Alembic commands ###
